bootpay:
  enabled: true
  pg: tosspayments
  mode: test
  js-application-id: ${BOOTPAY_JS_APPLICATION_ID:}
  rest-client-key: ${BOOTPAY_REST_CLIENT_KEY:}
  private-key: ${BOOTPAY_PRIVATE_KEY:}
  server-base-url: https://api.bootpay.co.kr
  customer-key-prefix: BIDEO_MEMBER_
