solapi:
  api-key: ${SOLAPI_API_KEY:}
  api-secret: ${SOLAPI_API_SECRET:}
  from-number: ${SOLAPI_FROM_NUMBER:}

app:
  mail:
    from-address: ${APP_MAIL_FROM_ADDRESS:${SPRING_MAIL_USERNAME:no-reply@bideo.local}}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
